### ISSUE TITLE
Thank you.

### ISSUE THREAD

**Issue by edorgeville** [mtraver/rpi-ir-remote#1]
I installed stretch instead of jessie by mistake and couldn't find why lirc wasn't working.
Your guide was very helpful.
Thanks again !

**Comment by mtraver** [comment]
Fantastic! I'm glad it was useful. Thanks for the note :)

**Comment by fredwangwang** [comment]
Another thanks here. Upgraded to kernel 4.19, suddenly everything stopped working. Your description literally saved me a night searching for why it doesn't work. Really appreciate your detailed debugging process!

**Comment by mtraver** [comment]
Glad to hear it helped!
