### ISSUE TITLE
Transmission failed

### ISSUE THREAD

**Issue by KoenHaemels** [mtraver/rpi-ir-remote#2]
Followed every step, but still stuck on the irsend command

irsend SEND_ONCE PANASONIC KEY_VOLUMEDOWN

transmission failed
Error running command: Input/output error

Any fix for this ?

**Comment by mtraver** [comment]
It's hard to say without more information. What version of Debian are you running? What version of LIRC? Step 5 sanity checks look good? Anything out of the ordinary in `dmesg` (add `debug=1` to `dtoverlay` to get more verbose logs)?

**Comment by KoenHaemels** [comment]
> It's hard to say without more information. What version of Debian are you running? What version of LIRC? Step 5 sanity checks look good? Anything out of the ordinary in `dmesg` (add `debug=1` to `dtoverlay` to get more verbose logs)?

Running it on a Raspberry Pi
- Linux raspberrypi 4.14.71+
- lirc-0.9.4c

Checks seems to be good ?

`dmesg | grep lirc`

[    8.185917] lirc_dev: IR Remote Control driver registered, major 243
[    8.197181] lirc_rpi: module is from the staging directory, the quality is unknown, you have been warned.
[    8.239241] lirc_rpi: to_irq 163
[    9.303227] lirc_rpi: auto-detected active high receiver on GPIO pin 23
[    9.303675] lirc_rpi lirc_rpi: lirc_dev: driver lirc_rpi registered at minor = 0
[    9.303687] lirc_rpi: driver registered!
[    9.303800] lirc_rpi: Interrupt 163 obtained
[    9.303815] lirc_rpi: in init_timing_params, freq=38000 pulse=13157, space=13158
[   27.849750] input: lircd-uinput as /devices/virtual/input/input0

`lsmod | grep lirc`

lirc_rpi                8001  2
lirc_dev                8313  1 lirc_rpi

`ll /dev/lirc0`

crw-rw---- 1 root video 243, 0 okt 29 16:29 /dev/lirc0

`ps aux | grep lirc`

root       247  0.0  0.4   4264  2092 ?        Ss   okt29   0:00 /usr/sbin/lircmd --nodaemon
root       260  0.0  0.4   4192  2100 ?        Ss   okt29   0:00 /usr/bin/irexec /etc/lirc/irexec.lircrc
root       391  0.0  0.8   7180  3896 ?        Ss   okt29   0:00 /usr/sbin/lircd --nodaemon
root       392  0.0  0.5   4268  2312 ?        Ss   okt29   0:00 /usr/sbin/lircd-uinput
pi        2210  0.0  0.4   4364  2112 pts/0    S+   11:08   0:00 grep --color=auto lirc


Running the command `irsend SEND_ONCE PANASONIC KEY_VOLUMEDOWN` outputs next:

okt 30 11:09:43 raspberrypi lircd[391]: lircd-0.9.4c[391]: Error: invalid send buffer
okt 30 11:09:43 raspberrypi lircd[391]: lircd-0.9.4c[391]: Error: this remote configuration cannot be used to transmit
okt 30 11:09:43 raspberrypi lircd[391]: lircd-0.9.4c[391]: Error: error processing command: SEND_ONCE PANASONIC KEY_VOLUMEDOWN
okt 30 11:09:43 raspberrypi lircd[391]: lircd-0.9.4c[391]: Error: transmission failed
okt 30 11:09:43 raspberrypi lircd[391]: lircd-0.9.4c[391]: Info: removed client
okt 30 11:09:43 raspberrypi lircd-0.9.4c[391]: Error: invalid send buffer
okt 30 11:09:43 raspberrypi lircd-0.9.4c[391]: Error: this remote configuration cannot be used to transmit
okt 30 11:09:43 raspberrypi lircd-0.9.4c[391]: Error: error processing command: SEND_ONCE PANASONIC KEY_VOLUMEDOWN
okt 30 11:09:43 raspberrypi lircd-0.9.4c[391]: Error: transmission failed
okt 30 11:09:43 raspberrypi lircd-0.9.4c[391]: Info: removed client

**Comment by mtraver** [comment]
I'd start by looking into `Error: invalid send buffer` and `Error: this remote configuration cannot be used to transmit`.

**Comment by MagicJohnJang** [comment]
Did you solve it?

**Comment by KoenHaemels** [comment]
I did solved it, but can't remember exactly how i did it.
Probably solved it by reinstalling everything and checking my components if they're not dead.

**Comment by newb0101** [comment]
Thanks KoenHaemeks, that totally helped 😭. Seem to have no problem using lirc1 to use irrecord but switching to lirc0 and irsend keeps giving me an error. I’m using the newest 2020 Buster and a PiW

**Comment by newb0101** [comment]
> I'd start by looking into `Error: invalid send buffer` and `Error: this remote configuration cannot be used to transmit`.

Also strange to see the same errors

**Comment by KoenHaemels** [comment]
> Thanks KoenHaemeks, that totally helped 😭. Seem to have no problem using lirc1 to use irrecord but switching to lirc0 and irsend keeps giving me an error. I’m using the newest 2020 Buster and a PiW

Hey newb0101,

Sorry i can't remember it exactly. But most of the time, reinstalling helped me with the issues. Or even look for another package.

**Comment by newb0101** [comment]
Lol well I ended up downgrading and installing an old Raspian Image from 2016-2017 Edition when I did the project before. Ran sudo apt-get install lirc and Basic configuration changes to /boot/config.txt /etc/modules and I ended up having to use the old hardware.conf file... now it worked for irsend but now irrecord is broken 😅 oddly enough mode2 works just fine for receiving the raw ir signals 🥴 kinda wish they’d just make a new build for buster stretch but the tools are there if you don’t mind the headache.. ps Im using the old way lirc overlay and all
